name: Code Quality

on:
  push:

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: 'poetry'
      - run: poetry install
      - run: poetry run pycodestyle .
      - run: poetry run black --check .
      - name: pylint
        run: poetry run pylint */
      - run: poetry run coverage run --source='.' -m pytest
      - run: poetry run coverage report
